### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by elijahcruz12** [programarivm/php-chess#16]
Is there currently a way to know that you can promote, as well as being able to choose which piece you promote to? It's not in the README, which is why I'm opening an issue to ask about this.

**Comment by programarivm** [comment]
Hello @elijahcruz12,

Thanks for the feedback! The README needs some review to include the events taking place.

At this moment there are six heuristics available (none of which considering pawn structures): Material, King safety, Center, Connectivity, Space and Attack. The data can be visualized at [Heuristics Quest](https://programarivm.github.io/heuristics-quest/#/home).

However, the [promotion event](https://github.com/programarivm/php-chess/blob/master/src/Event/Promotion.php) (which is a completely different thing from a heuristic) is actually triggered when a pawn is promoted. 

The [corresponding test](https://github.com/programarivm/php-chess/blob/master/tests/unit/Event/PromotionTest.php) shows how to use this one.

**Comment by programarivm** [comment]
The `events()` method has been implemented in `Chess\Game` and the README is updated.
